global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rison-app-metrics'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['rison-backend:4000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['rison-node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['rison-cadvisor:8080']
