// src/api/routes/assessmentRouter.ts
import { Router } from "express";
import { query } from "../../lib/db";
import { ensureJobAssessment } from "../../lib/assessmentService";
import { sendAssessmentInviteEmail, sendInterviewScheduleEmail } from "../../lib/email";
import { kekaWorkflowService } from "../../integrations/keka/services/workflow.service";
import crypto from "crypto";
import { tenantStorage } from "../../lib/tenantContext.js";
import { queryGlobal } from "../../lib/tenantDb.js";

const router = Router();

// Middleware to resolve tenant context for guest candidates
async function resolveTenantContext(req: any, res: any, next: any) {
  // If recruiter/owner is logged in, authMiddleware has already set tenant context
  if (req.user && req.user.tenantId) {
    return next();
  }

  try {
    let tenantId: string | null = null;

    // 1. Resolve by assessment token
    const token = req.params.token || req.body.token || req.query.token;
    if (token && typeof token === "string" && token.length > 20) {
      const result = await queryGlobal("SELECT tenant_id FROM candidates WHERE assessment_token = $1 LIMIT 1;", [token]);
      if (result.rowCount && result.rowCount > 0) {
        tenantId = result.rows[0].tenant_id;
      }
    }

    // 2. Resolve by candidateId
    const candidateId = req.body.candidateId || req.query.candidateId;
    if (!tenantId && candidateId && typeof candidateId === "string") {
      const result = await queryGlobal("SELECT tenant_id FROM candidates WHERE id = $1 LIMIT 1;", [candidateId]);
      if (result.rowCount && result.rowCount > 0) {
        tenantId = result.rows[0].tenant_id;
      }
    }

    // 3. Resolve by jobId
    const jobId = req.body.jobId || req.params.jobId || req.query.jobId;
    if (!tenantId && jobId && typeof jobId === "string") {
      const result = await queryGlobal("SELECT tenant_id FROM jobs WHERE id = $1 LIMIT 1;", [jobId]);
      if (result.rowCount && result.rowCount > 0) {
        tenantId = result.rows[0].tenant_id;
      }
    }

    if (tenantId) {
      tenantStorage.run({ tenantId, userId: "guest", role: "candidate" }, () => {
        next();
      });
    } else {
      next();
    }
  } catch (err) {
    next(err);
  }
}

router.use(resolveTenantContext);

/**
 * POST /api/assessment/generate
 * Generates an assessment for a job title/description if it doesn't already exist.
 */
router.post("/generate", async (req: any, res: any) => {
  try {
    const { jobTitle, jobDescription, jobId } = req.body as {
      jobTitle: string;
      jobDescription: string;
      jobId?: string;
    };

    if (!jobTitle || !jobDescription) {
      return res.status(400).json({ error: "jobTitle and jobDescription are required" });
    }

    const id = jobId || `job-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
    
    // Ensure the job exists in the jobs table
    const checkJob = await query(`SELECT id FROM jobs WHERE id = $1;`, [id]);
    if (!checkJob.rowCount || checkJob.rowCount === 0) {
      await query(
        `INSERT INTO jobs (id, title, description) VALUES ($1, $2, $3);`,
        [id, jobTitle, jobDescription]
      );
    }

    const assessmentId = await ensureJobAssessment(id, jobTitle, jobDescription);
    res.json({ success: true, jobId: id, assessmentId });
  } catch (err: any) {
    console.error("Assessment generation route failed:", err);
    res.status(500).json({ error: err.message || "Failed to generate assessment" });
  }
});

/**
 * POST /api/assessment/send
 * Sends assessment invite to a shortlisted candidate.
 */
router.post("/send", async (req: any, res: any) => {
  try {
    const { candidateId } = req.body as { candidateId: string };
    if (!candidateId) {
      return res.status(400).json({ error: "candidateId is required" });
    }

    // Fetch candidate
    const candidateRes = await query(
      `SELECT * FROM candidates WHERE id = $1 LIMIT 1;`,
      [candidateId]
    );

    if (!candidateRes.rowCount || candidateRes.rowCount === 0) {
      return res.status(404).json({ error: "Candidate not found" });
    }

    const candidate = candidateRes.rows[0];

    // Ensure job exists and matches role (backwards compatibility)
    let jobId = candidate.job_id;
    if (!jobId) {
      // Find or create job based on role
      const jobRes = await query(`SELECT id FROM jobs WHERE title = $1 LIMIT 1;`, [candidate.role]);
      if (jobRes.rowCount && jobRes.rowCount > 0) {
        jobId = jobRes.rows[0].id;
      } else {
        jobId = `job-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
        await query(
          `INSERT INTO jobs (id, title, description) VALUES ($1, $2, $3);`,
          [jobId, candidate.role, `Autogenerated job description for ${candidate.role}`]
        );
      }
      // Update candidate with job_id
      await query(`UPDATE candidates SET job_id = $1 WHERE id = $2;`, [jobId, candidateId]);
    }

    // Ensure job assessment exists
    const jobDesc = `Autogenerated job description for ${candidate.role}`;
    await ensureJobAssessment(jobId, candidate.role, jobDesc);

    // Generate token
    const token = crypto.randomBytes(24).toString("hex");
    const expiry = new Date();
    expiry.setDate(expiry.getDate() + 7); // 7 days expiry

    await query(
      `UPDATE candidates 
       SET assessment_token = $1, assessment_token_expiry = $2, assessment_status = $3
       WHERE id = $4;`,
      [token, expiry, "pending", candidateId]
    );

    // Log activity
    await query(
      `INSERT INTO candidate_activity_logs (candidate_id, event_type, message)
       VALUES ($1, $2, $3);`,
      [candidateId, "assessment_invited", `Assessment invitation email sent. Link: /assessment/${token}`]
    );

    // Send the email
    await sendAssessmentInviteEmail({
      candidateName: candidate.name,
      candidateEmail: candidate.email,
      jobTitle: candidate.role,
      token,
      expiryDate: expiry,
    });

    res.json({ success: true, token, expiryDate: expiry });
  } catch (err: any) {
    console.error("Assessment send invite failed:", err);
    res.status(500).json({ error: err.message || "Failed to send assessment invitation" });
  }
});

/**
 * GET /api/assessment/:token
 * Candidate portal entry endpoint. Loads test and locks attempts.
 */
router.get("/:token", async (req: any, res: any) => {
  try {
    const { token } = req.params;
    const { sessionId } = req.query as { sessionId: string };

    if (!sessionId) {
      return res.status(400).json({ error: "sessionId query parameter is required to initialize session" });
    }

    // Fetch candidate by token
    const candidateRes = await query(
      `SELECT c.*, j.title as job_title, j.description as job_description
       FROM candidates c
       LEFT JOIN jobs j ON c.job_id = j.id
       WHERE c.assessment_token = $1 LIMIT 1;`,
      [token]
    );

    if (!candidateRes.rowCount || candidateRes.rowCount === 0) {
      return res.status(404).json({ error: "Invalid or expired assessment link" });
    }

    const candidate = candidateRes.rows[0];

    // Check token expiry
    if (new Date(candidate.assessment_token_expiry) < new Date()) {
      return res.status(400).json({ error: "This assessment link has expired (7 days deadline passed)" });
    }

    // Find assessment for the job
    const assessmentRes = await query(
      `SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`,
      [candidate.job_id]
    );

    if (!assessmentRes.rowCount || assessmentRes.rowCount === 0) {
      return res.status(404).json({ error: "Assessment not found for this job opening" });
    }

    const assessmentId = assessmentRes.rows[0].id;

    // Check if there is an existing attempt
    const attemptRes = await query(
      `SELECT * FROM assessment_attempts WHERE candidate_id = $1 AND assessment_id = $2 LIMIT 1;`,
      [candidate.id, assessmentId]
    );

    let attempt;

    // Fetch questions (omit the correct answers for the candidate!)
    const questionsRes = await query(
      `SELECT id, question_text, options, difficulty, topic 
       FROM assessment_questions 
       WHERE assessment_id = $1 
       ORDER BY id ASC;`,
      [assessmentId]
    );
    const questions = questionsRes.rows.map(q => ({
      id: q.id,
      questionText: q.question_text,
      options: typeof q.options === "string" ? JSON.parse(q.options) : q.options,
      difficulty: q.difficulty,
      topic: q.topic
    }));

    const TOTAL_TEST_TIME_SEC = 10 * 60; // 10 minutes

    if (!attemptRes.rowCount || attemptRes.rowCount === 0) {
      // Use the session ID passed by the frontend to prevent race conditions during double-fetch
      const sessionDbId = sessionId || crypto.randomUUID();
      // Capture client info for audit
      const browserFingerprint = req.headers['user-agent'] || null;
      const ipAddress = req.ip || req.headers['x-forwarded-for'] || null;
      // Create a new session record (attempt_id will be linked after attempt creation)
      await query(
        `INSERT INTO assessment_sessions (id, candidate_id, assessment_id, attempt_id, status, browser_fingerprint, ip_address)
         VALUES ($1, $2, $3, NULL, $4, $5, $6);`,
        [sessionDbId, candidate.id, assessmentId, 'active', browserFingerprint, ipAddress]
      );
      // Create a brand new attempt linked to this session
      const attemptId = `attempt-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
      await query(
        `INSERT INTO assessment_attempts (id, candidate_id, assessment_id, status, session_id)
         VALUES ($1, $2, $3, $4, $5);`,
        [attemptId, candidate.id, assessmentId, "started", sessionDbId]
      );
      // Update the session with the attempt reference
      await query(
        `UPDATE assessment_sessions SET attempt_id = $1 WHERE id = $2;`,
        [attemptId, sessionDbId]
      );

      // Log activity
      await query(
        `INSERT INTO candidate_activity_logs (candidate_id, event_type, message)
         VALUES ($1, $2, $3);`,
        [candidate.id, "assessment_started", "Candidate started the assessment test."]
      );

      return res.json({
        success: true,
        candidateName: candidate.name,
        candidateEmail: candidate.email,
        jobTitle: candidate.role,
        remainingSeconds: TOTAL_TEST_TIME_SEC,
        questions,
        sessionId: sessionDbId,
      });
    } else {
      attempt = attemptRes.rows[0];

      // If attempt is already completed, deny access
      if (attempt.status === "completed") {
        return res.status(403).json({ error: "Assessment already completed and submitted." });
      }

      // Rejoining session checks:
      // Check session ID
      if (attempt.session_id !== sessionId) {
        return res.status(403).json({
          error: "Only one active session allowed. You cannot open this assessment in multiple windows/tabs."
        });
      }

      // Check remaining time
      const elapsedMs = Date.now() - new Date(attempt.started_at).getTime();
      const elapsedSec = Math.floor(elapsedMs / 1000);
      const remainingSeconds = TOTAL_TEST_TIME_SEC - elapsedSec;

      if (remainingSeconds <= 0) {
        // Force submit
        return res.status(403).json({
          error: "Time limit expired. The assessment has been automatically closed.",
          expired: true
        });
      }

      return res.json({
        success: true,
        candidateName: candidate.name,
        candidateEmail: candidate.email,
        jobTitle: candidate.role,
        remainingSeconds,
        questions,
      });
    }
  } catch (err: any) {
    console.error("Failed to load assessment portal details:", err);
    res.status(500).json({ error: err.message || "Failed to load assessment details" });
  }
});

// POST /api/assessment/:token/heartbeat - updates session heartbeat
router.post("/:token/heartbeat", async (req: any, res: any) => {
  try {
    const { token } = req.params;
    const { sessionId } = req.body as { sessionId: string };
    if (!sessionId) { return res.status(400).json({ error: "sessionId required" }); }
    // Update heartbeat timestamp
    await query(
      `UPDATE assessment_sessions SET last_heartbeat = now() WHERE id = $1 AND candidate_id = (SELECT id FROM candidates WHERE assessment_token = $2);`,
      [sessionId, token]
    );
    res.json({ success: true });
  } catch (err:any) {
    console.error("Heartbeat failed:", err);
    res.status(500).json({ error: err.message || "Failed heartbeat" });
  }
});

// POST /api/assessment/:token/force-resume - abandon existing session and create new one
router.post("/:token/force-resume", async (req: any, res: any) => {
  try {
    const { token } = req.params;
    const { oldSessionId } = req.body as { oldSessionId: string };
    // Mark old session as abandoned
    if (oldSessionId) {
      await query(`UPDATE assessment_sessions SET status = 'abandoned' WHERE id = $1;`, [oldSessionId]);
    }
    // Generate new session
    const newSessionId = crypto.randomUUID();
    const candidateRes = await query(`SELECT id, job_id FROM candidates WHERE assessment_token = $1 LIMIT 1;`, [token]);
    if (!candidateRes.rowCount) { return res.status(404).json({ error: "Invalid token" }); }
    const candidate = candidateRes.rows[0];
    const assessmentRes = await query(`SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`, [candidate.job_id]);
    if (!assessmentRes.rowCount) { return res.status(404).json({ error: "Assessment not found" }); }
    const assessmentId = assessmentRes.rows[0].id;
    const browserFingerprint = req.headers['user-agent'] || null;
    const ipAddress = req.ip || req.headers['x-forwarded-for'] || null;
    await query(
      `INSERT INTO assessment_sessions (id, candidate_id, assessment_id, attempt_id, status, browser_fingerprint, ip_address) VALUES ($1, $2, $3, NULL, $4, $5, $6);`,
      [newSessionId, candidate.id, assessmentId, 'active', browserFingerprint, ipAddress]
    );

    // Check if there is an existing attempt
    const attemptRes = await query(
      `SELECT * FROM assessment_attempts WHERE candidate_id = $1 AND assessment_id = $2 LIMIT 1;`,
      [candidate.id, assessmentId]
    );

    let activeAttemptId;
    if (attemptRes.rowCount && attemptRes.rowCount > 0) {
      const existingAttempt = attemptRes.rows[0];
      if (existingAttempt.status === "completed") {
        return res.status(400).json({ error: "Assessment already completed and submitted." });
      }
      activeAttemptId = existingAttempt.id;
      // Update session_id on the existing attempt
      await query(
        `UPDATE assessment_attempts SET session_id = $1 WHERE id = $2;`,
        [newSessionId, activeAttemptId]
      );
    } else {
      // Create new attempt linked to new session
      activeAttemptId = `attempt-${Date.now()}-${Math.random().toString(36).substr(2,5)}`;
      await query(
        `INSERT INTO assessment_attempts (id, candidate_id, assessment_id, status, session_id) VALUES ($1, $2, $3, $4, $5);`,
        [activeAttemptId, candidate.id, assessmentId, "started", newSessionId]
      );
    }

    // Update session with active attempt id
    await query(`UPDATE assessment_sessions SET attempt_id = $1 WHERE id = $2;`, [activeAttemptId, newSessionId]);
    res.json({ success: true, sessionId: newSessionId });
  } catch (err:any) {
    console.error("Force resume failed:", err);
    res.status(500).json({ error: err.message || "Failed force resume" });
  }
});

// Continue with existing routes...

/**
 * POST /api/assessment/submit
 * Candidate finishes the test and submits responses. Calculates final rankings.
 */
router.post("/submit", async (req: any, res: any) => {
  try {
    const { token, answers, sessionId, timeTaken } = req.body as {
      token: string;
      answers: Record<string, string>;
      sessionId: string;
      timeTaken: number; // in seconds
    };

    if (!token || !sessionId) {
      return res.status(400).json({ error: "token and sessionId are required" });
    }

    // Fetch candidate
    const candidateRes = await query(
      `SELECT * FROM candidates WHERE assessment_token = $1 LIMIT 1;`,
      [token]
    );

    if (!candidateRes.rowCount || candidateRes.rowCount === 0) {
      return res.status(404).json({ error: "Invalid candidate token" });
    }

    const candidate = candidateRes.rows[0];

    // Find assessment
    const assessmentRes = await query(
      `SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`,
      [candidate.job_id]
    );

    if (!assessmentRes.rowCount || assessmentRes.rowCount === 0) {
      return res.status(404).json({ error: "Assessment not found" });
    }

    const assessmentId = assessmentRes.rows[0].id;

    // Get attempt
    const attemptRes = await query(
      `SELECT * FROM assessment_attempts WHERE candidate_id = $1 AND assessment_id = $2 LIMIT 1;`,
      [candidate.id, assessmentId]
    );

    if (!attemptRes.rowCount || attemptRes.rowCount === 0) {
      return res.status(400).json({ error: "No attempt session found for this candidate" });
    }

    const attempt = attemptRes.rows[0];

    if (attempt.status === "completed") {
      return res.status(400).json({ error: "Assessment has already been submitted." });
    }

    // Verify session
    if (attempt.session_id !== sessionId) {
      return res.status(403).json({ error: "Invalid session credentials" });
    }

    // Calculate score
    const questionsRes = await query(
      `SELECT id, correct_answer FROM assessment_questions WHERE assessment_id = $1;`,
      [assessmentId]
    );

    let correctCount = 0;
    let incorrectCount = 0;

    questionsRes.rows.forEach(q => {
      const candidateAns = answers[q.id];
      if (candidateAns && candidateAns.trim().toLowerCase() === q.correct_answer.trim().toLowerCase()) {
        correctCount++;
      } else {
        incorrectCount++;
      }
    });

    const totalQuestions = questionsRes.rowCount || 10;
    const assessmentScore = Math.round((correctCount / totalQuestions) * 100);

    // Save completed attempt
    await query(
      `UPDATE assessment_attempts
       SET status = $1, correct_answers = $2, incorrect_answers = $3, score = $4, time_taken = $5, completed_at = now()
       WHERE id = $6;`,
      ["completed", correctCount, incorrectCount, assessmentScore, timeTaken, attempt.id]
    );

    // Calculate Final Integrated Score
    // Final Score = (Resume Score * 40%) + (Assessment Score * 60%)
    const resumeScore = candidate.score || 0;
    const finalScore = Number(((resumeScore * 0.4) + (assessmentScore * 0.6)).toFixed(1));

    // Rank candidate
    let nextStatus = "Review";
    let kekaStatus = "active";
    let assessmentStatus = "failed";

    if (finalScore >= 80) {
      nextStatus = "Qualified";
      assessmentStatus = "passed";
    } else if (finalScore >= 60) {
      nextStatus = "Review";
      assessmentStatus = "passed"; // passed assessment, but overall score is in review range
    } else {
      nextStatus = "Rejected";
      kekaStatus = "rejected_pool";
      assessmentStatus = "failed";
    }

    // Update candidate
    await query(
      `UPDATE candidates 
       SET assessment_score = $1, assessment_status = $2, final_score = $3, status = $4, keka_status = $5, assessment_completed_at = now()
       WHERE id = $6;`,
      [assessmentScore, assessmentStatus, finalScore, nextStatus, kekaStatus, candidate.id]
    );

    // Sync assessment completion stage with Keka ATS Integration Foundation
    try {
      await kekaWorkflowService.handleAssessmentCompletion(candidate.id, finalScore);
    } catch (kekaErr) {
      console.error("⚠️ Failed to sync assessment completion to Keka:", kekaErr);
    }

    // Log Activity
    await query(
      `INSERT INTO candidate_activity_logs (candidate_id, event_type, message)
       VALUES ($1, $2, $3);`,
      [
        candidate.id,
        "assessment_submitted",
        `Assessment completed. Score: ${assessmentScore}% (Correct: ${correctCount}/${totalQuestions}). Final score calculated: ${finalScore}% (Ranked: ${nextStatus}).`
      ]
    );

    // Automation: If candidate rank is Qualified, schedule HR interview automatically!
    let interviewDetails = null;
    if (nextStatus === "Qualified") {
      // Schedule interview 2 days from now at 10:00 AM
      const interviewDate = new Date();
      interviewDate.setDate(interviewDate.getDate() + 2);
      interviewDate.setHours(10, 0, 0, 0);

      const interviewId = `interview-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
      await query(
        `INSERT INTO interviews (id, candidate_id, job_id, scheduled_date, status)
         VALUES ($1, $2, $3, $4, $5);`,
        [interviewId, candidate.id, candidate.job_id, interviewDate, "scheduled"]
      );

      // Log interview scheduling
      await query(
        `INSERT INTO candidate_activity_logs (candidate_id, event_type, message)
         VALUES ($1, $2, $3);`,
        [
          candidate.id,
          "interview_scheduled",
          `HR Interview automatically scheduled for ${interviewDate.toLocaleDateString()} at 10:00 AM.`
        ]
      );

      // Update candidate details for legacy screen support
      await query(
        `UPDATE candidates 
         SET status = 'interviewing', interview_scheduled_date = $1 
         WHERE id = $2;`,
        [interviewDate, candidate.id]
      );

      // Trigger automatic emails (Candidate and HR)
      try {
        await sendInterviewScheduleEmail({
          candidateName: candidate.name,
          candidateEmail: candidate.email,
          jobTitle: candidate.role,
          resumeScore,
          assessmentScore,
          finalScore,
          scheduledDate: interviewDate,
          hrEmail: "yogeshkumarwadhwa@localhost.com", // HR recipient email
        });
      } catch (mailErr) {
        console.error("Failed to trigger automated interview emails:", mailErr);
      }

      interviewDetails = {
        scheduledDate: interviewDate,
        status: "scheduled"
      };
    }

    res.json({
      success: true,
      assessmentScore,
      finalScore,
      status: nextStatus,
      correctAnswers: correctCount,
      totalQuestions,
      interviewDetails
    });
  } catch (err: any) {
    console.error("Failed to submit assessment responses:", err);
    res.status(500).json({ error: err.message || "Failed to submit assessment" });
  }
});

/**
 * POST /api/assessment/violation
 * Logs an exam violation and increments the violation counts.
 */
router.post("/violation", async (req: any, res: any) => {
  try {
    const { token, violationType, details } = req.body as {
      token: string;
      violationType: string;
      details: string;
    };

    if (!token || !violationType) {
      return res.status(400).json({ error: "token and violationType are required" });
    }

    // Fetch candidate
    const candidateRes = await query(
      `SELECT id, job_id, violation_count FROM candidates WHERE assessment_token = $1 LIMIT 1;`,
      [token]
    );

    if (!candidateRes.rowCount || candidateRes.rowCount === 0) {
      return res.status(404).json({ error: "Invalid token" });
    }

    const candidate = candidateRes.rows[0];

    // Find assessment
    const assessmentRes = await query(
      `SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`,
      [candidate.job_id]
    );

    if (!assessmentRes.rowCount || assessmentRes.rowCount === 0) {
      return res.status(404).json({ error: "Assessment not found" });
    }

    const assessmentId = assessmentRes.rows[0].id;

    // Get attempt
    const attemptRes = await query(
      `SELECT id, violation_count FROM assessment_attempts WHERE candidate_id = $1 AND assessment_id = $2 LIMIT 1;`,
      [candidate.id, assessmentId]
    );

    if (!attemptRes.rowCount || attemptRes.rowCount === 0) {
      return res.status(400).json({ error: "No active attempt found" });
    }

    const attempt = attemptRes.rows[0];

    // Insert violation
    await query(
      `INSERT INTO assessment_violations (candidate_id, attempt_id, violation_type, details)
       VALUES ($1, $2, $3, $4);`,
      [candidate.id, attempt.id, violationType, details]
    );

    // Update violation counts
    const newAttemptViolations = (attempt.violation_count || 0) + 1;
    const newCandidateViolations = (candidate.violation_count || 0) + 1;

    await query(
      `UPDATE assessment_attempts SET violation_count = $1 WHERE id = $2;`,
      [newAttemptViolations, attempt.id]
    );

    await query(
      `UPDATE candidates SET violation_count = $1 WHERE id = $2;`,
      [newCandidateViolations, candidate.id]
    );

    // Log to activity logs
    await query(
      `INSERT INTO candidate_activity_logs (candidate_id, event_type, message)
       VALUES ($1, $2, $3);`,
      [candidate.id, "assessment_violation", `Violation detected: ${details}`]
    );

    console.warn(`⚠️ Security Violation logged for candidate ${candidate.id}: ${details}`);
    res.json({ success: true, count: newAttemptViolations });
  } catch (err: any) {
    console.error("Failed to log security violation:", err);
    res.status(500).json({ error: err.message || "Failed to log violation" });
  }
});

/**
 * GET /api/candidate/results
 * Fetches assessment attempt details to display on the result scorecard page.
 */
router.get("/results/get", async (req: any, res: any) => {
  try {
    const { token } = req.query as { token: string };

    if (!token) {
      return res.status(400).json({ error: "token parameter is required" });
    }

    const candidateRes = await query(
      `SELECT c.*, j.title as job_title 
       FROM candidates c
       LEFT JOIN jobs j ON c.job_id = j.id
       WHERE c.assessment_token = $1 LIMIT 1;`,
      [token]
    );

    if (!candidateRes.rowCount || candidateRes.rowCount === 0) {
      return res.status(404).json({ error: "Candidate not found" });
    }

    const candidate = candidateRes.rows[0];

    // Find assessment attempt details
    const attemptRes = await query(
      `SELECT * FROM assessment_attempts WHERE candidate_id = $1 ORDER BY started_at DESC LIMIT 1;`,
      [candidate.id]
    );

    if (!attemptRes.rowCount || attemptRes.rowCount === 0) {
      return res.status(404).json({ error: "No assessment attempts found for this candidate" });
    }

    const attempt = attemptRes.rows[0];

    // Status mapping: PASS or FAIL
    const testStatus = candidate.assessment_score >= 70 ? "PASS" : "FAIL";

    res.json({
      success: true,
      candidateName: candidate.name,
      jobRole: candidate.role,
      resumeScore: candidate.score,
      assessmentScore: candidate.assessment_score,
      finalScore: Number(candidate.final_score),
      totalQuestions: 10,
      correctAnswers: attempt.correct_answers,
      incorrectAnswers: attempt.incorrect_answers,
      timeTaken: attempt.time_taken,
      violationCount: attempt.violation_count,
      status: testStatus,
      rankingStatus: candidate.status,
    });
  } catch (err: any) {
    console.error("Failed to fetch candidate assessment results:", err);
    res.status(500).json({ error: err.message || "Failed to retrieve results" });
  }
});

// GET /api/assessment/job-info/:jobId - fetches job details for public portal
router.get("/job-info/:jobId", async (req: any, res: any) => {
  try {
    const { jobId } = req.params;
    const jobRes = await query(`SELECT title, description FROM jobs WHERE id = $1 LIMIT 1;`, [jobId]);
    if (!jobRes.rowCount || jobRes.rowCount === 0) {
      return res.status(404).json({ error: "Job opening not found." });
    }
    const job = jobRes.rows[0];
    // Check if there is an active assessment for this job
    const assessmentRes = await query(`SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`, [jobId]);
    if (!assessmentRes.rowCount || assessmentRes.rowCount === 0) {
      return res.status(404).json({ error: "No assessment configured for this job opening." });
    }
    res.json({ title: job.title, description: job.description });
  } catch (err: any) {
    console.error("Failed to load job details:", err);
    res.status(500).json({ error: err.message || "Failed to load job details" });
  }
});

// POST /api/assessment/public-register - registers a candidate dynamically from a public link
router.post("/public-register", async (req: any, res: any) => {
  try {
    const { jobId, name, email, phone } = req.body as {
      jobId: string;
      name: string;
      email: string;
      phone?: string;
    };

    if (!jobId || !name || !email) {
      return res.status(400).json({ error: "jobId, name, and email are required." });
    }

    // 1. Fetch job to make sure it exists
    const jobRes = await query(`SELECT title, tenant_id FROM jobs WHERE id = $1 LIMIT 1;`, [jobId]);
    if (!jobRes.rowCount || jobRes.rowCount === 0) {
      return res.status(404).json({ error: "Job opening not found." });
    }
    const job = jobRes.rows[0];

    // 2. Fetch assessment to make sure it exists
    const assessmentRes = await query(`SELECT id FROM assessments WHERE job_id = $1 LIMIT 1;`, [jobId]);
    if (!assessmentRes.rowCount || assessmentRes.rowCount === 0) {
      return res.status(404).json({ error: "Assessment not configured for this job opening." });
    }

    // 3. Check if candidate is already registered for this job
    const candidateCheck = await query(
      `SELECT assessment_token, assessment_status FROM candidates WHERE email = $1 AND job_id = $2 LIMIT 1;`,
      [email, jobId]
    );

    if (candidateCheck.rowCount && candidateCheck.rowCount > 0) {
      const existingCandidate = candidateCheck.rows[0];
      return res.json({ 
        success: true, 
        token: existingCandidate.assessment_token, 
        message: "Retrieved existing test registration link.",
        assessmentStatus: existingCandidate.assessment_status
      });
    }

    // 4. Register new candidate
    const candidateId = `cnd-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
    const token = crypto.randomBytes(24).toString("hex");
    const expiry = new Date();
    expiry.setDate(expiry.getDate() + 7); // 7 days expiry
    const appliedDate = new Date().toISOString().split("T")[0];

    await query(
      `INSERT INTO candidates (
        id, name, email, phone, role, score, match_percent, experience_years, 
        status, application_source, job_id, assessment_token, assessment_token_expiry, assessment_status, applied_date, tenant_id
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16);`,
      [
        candidateId, name, email, phone || null, job.title, 0, 0, 0, 
        "applied", "public_link", jobId, token, expiry, "pending", appliedDate, job.tenant_id
      ]
    );

    // Log activity
    await query(
      `INSERT INTO candidate_activity_logs (candidate_id, event_type, message, tenant_id)
       VALUES ($1, $2, $3, $4);`,
      [candidateId, "assessment_invited", `Public link registration. Token generated: ${token}`, job.tenant_id]
    );

    res.json({ success: true, token });
  } catch (err: any) {
    console.error("Failed to register public candidate:", err);
    res.status(500).json({ error: err.message || "Failed to register candidate" });
  }
});

export default router;
